"""add admin_audit_log

Revision ID: 538fe233b639
Revises: 508df0110037
Create Date: 2026-04-23 13:49:54.128263

Spec #38 (E-018a) — admin audit log. One row per admin-scoped HTTP
request; written fire-and-forget from the `audit_admin_request` FastAPI
dependency so audit I/O never blocks responses.

Note: autogenerate wanted to drop `ix_cards_category_id_active` and
`ix_cards_embedding_ivfflat` because those indexes live on the DB but
are not declared on the `Card` ORM model. They were added by earlier
migrations (d16ca29a5d08 and predecessors) and remain live — those drops
are false positives and have been scrubbed from this migration (same
precedent as `f3350dcba3a5`).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '538fe233b639'
down_revision: Union[str, Sequence[str], None] = '508df0110037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_log',
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_audit_admin_created', 'admin_audit_log', ['admin_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_admin_id'), 'admin_audit_log', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    op.create_index('ix_admin_audit_route_created', 'admin_audit_log', ['route', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_audit_route_created', table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_admin_id'), table_name='admin_audit_log')
    op.drop_index('ix_admin_audit_admin_created', table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    # ### end Alembic commands ###
