"""add card_progress table

Revision ID: 638a23f7c9ed
Revises: 9bb18657d55d
Create Date: 2026-04-09 06:55:17.713815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638a23f7c9ed'
down_revision: Union[str, Sequence[str], None] = '9bb18657d55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_progress',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty_fsrs', sa.Float(), nullable=False),
    sa.Column('elapsed_days', sa.Float(), nullable=False),
    sa.Column('scheduled_days', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_card_progress_user_card')
    )
    op.create_index(op.f('ix_card_progress_card_id'), 'card_progress', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_progress_user_id'), 'card_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_progress_user_id'), table_name='card_progress')
    op.drop_index(op.f('ix_card_progress_card_id'), table_name='card_progress')
    op.drop_table('card_progress')
    # ### end Alembic commands ###
