"""add target_company and target_date to users

Revision ID: 74a6fb27a181
Revises: a4f1d8e73b92
Create Date: 2026-04-11 07:47:14.149807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a6fb27a181'
down_revision: Union[str, Sequence[str], None] = 'a4f1d8e73b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_company', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('target_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'target_date')
    op.drop_column('users', 'target_company')
    # ### end Alembic commands ###
