"""add gamification tables

Revision ID: 802d5ba2e219
Revises: fdc5af6f825f
Create Date: 2026-04-09 22:21:17.072218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802d5ba2e219'
down_revision: Union[str, Sequence[str], None] = 'fdc5af6f825f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('threshold_type', sa.String(length=32), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamification_stats',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('freezes_available', sa.Integer(), nullable=False),
    sa.Column('freeze_week_start', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_badges',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('badge_id', sa.String(length=64), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badges_user_badge')
    )
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)

    # Seed the static badge catalog. Mirrored in
    # app/services/gamification_service.BADGES — keep both in sync.
    badges_table = sa.table(
        'badges',
        sa.column('id', sa.String),
        sa.column('name', sa.String),
        sa.column('description', sa.String),
        sa.column('threshold_type', sa.String),
        sa.column('threshold_value', sa.Integer),
    )
    op.bulk_insert(
        badges_table,
        [
            {'id': 'first_review', 'name': 'First Step', 'description': 'Reviewed your first card', 'threshold_type': 'event', 'threshold_value': 0},
            {'id': 'streak_3', 'name': 'On a Roll', 'description': '3-day streak', 'threshold_type': 'streak', 'threshold_value': 3},
            {'id': 'streak_7', 'name': 'One Week Strong', 'description': '7-day streak', 'threshold_type': 'streak', 'threshold_value': 7},
            {'id': 'streak_30', 'name': 'Habit Formed', 'description': '30-day streak', 'threshold_type': 'streak', 'threshold_value': 30},
            {'id': 'streak_100', 'name': 'Centurion', 'description': '100-day streak', 'threshold_type': 'streak', 'threshold_value': 100},
            {'id': 'xp_100', 'name': 'Apprentice', 'description': 'Earned 100 XP', 'threshold_type': 'xp', 'threshold_value': 100},
            {'id': 'xp_500', 'name': 'Journeyman', 'description': 'Earned 500 XP', 'threshold_type': 'xp', 'threshold_value': 500},
            {'id': 'xp_2000', 'name': 'Expert', 'description': 'Earned 2000 XP', 'threshold_type': 'xp', 'threshold_value': 2000},
            {'id': 'xp_10000', 'name': 'Master', 'description': 'Earned 10000 XP', 'threshold_type': 'xp', 'threshold_value': 10000},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_table('gamification_stats')
    op.drop_table('badges')
    # ### end Alembic commands ###
