"""add cards deleted_at for soft delete

Revision ID: b1674f79f780
Revises: c9863b51075d
Create Date: 2026-04-10 06:05:42.151302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1674f79f780'
down_revision: Union[str, Sequence[str], None] = 'c9863b51075d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'deleted_at')
    # ### end Alembic commands ###
