"""add scan_id skills_matched skills_missing to tracker

Revision ID: e4eab11b8e33
Revises: f75789e4967f
Create Date: 2026-04-11 08:36:14.826163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4eab11b8e33'
down_revision: Union[str, Sequence[str], None] = 'f75789e4967f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker_applications_v2', sa.Column('scan_id', sa.String(length=36), nullable=True))
    op.add_column('tracker_applications_v2', sa.Column('skills_matched', sa.Text(), nullable=True))
    op.add_column('tracker_applications_v2', sa.Column('skills_missing', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tracker_applications_v2_scan_id'), 'tracker_applications_v2', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracker_applications_v2_scan_id'), table_name='tracker_applications_v2')
    op.drop_column('tracker_applications_v2', 'skills_missing')
    op.drop_column('tracker_applications_v2', 'skills_matched')
    op.drop_column('tracker_applications_v2', 'scan_id')
    # ### end Alembic commands ###
