"""add registration_logs table

Revision ID: f75789e4967f
Revises: 74a6fb27a181
Create Date: 2026-04-11 08:20:27.529872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75789e4967f'
down_revision: Union[str, Sequence[str], None] = '74a6fb27a181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_logs',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('google_email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_logs_ip_address'), 'registration_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_registration_logs_user_id'), 'registration_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_logs_user_id'), table_name='registration_logs')
    op.drop_index(op.f('ix_registration_logs_ip_address'), table_name='registration_logs')
    op.drop_table('registration_logs')
    # ### end Alembic commands ###
