"""add fsrs_step to card_progress

Revision ID: fdc5af6f825f
Revises: 638a23f7c9ed
Create Date: 2026-04-09 07:17:04.033930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc5af6f825f'
down_revision: Union[str, Sequence[str], None] = '638a23f7c9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_progress', sa.Column('fsrs_step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_progress', 'fsrs_step')
    # ### end Alembic commands ###
