"""Backward-compat shim — imports moved to app.schemas.responses."""
from app.schemas.responses import (  # noqa: F401
    ATSScoreBreakdown,
    AnalysisResponse,
    BulletAnalysis,
    CoverLetterResponse,
    ErrorResponse,
    FormattingIssue,
    InterviewPrepResponse,
    InterviewQuestion,
    KeywordChartData,
    RewriteEntry,
    RewriteHeader,
    RewriteResponse,
    RewriteSection,
    SkillGap,
    SkillOverlapData,
    TrackerApplication,
)

__all__ = [
    "ATSScoreBreakdown",
    "AnalysisResponse",
    "BulletAnalysis",
    "CoverLetterResponse",
    "ErrorResponse",
    "FormattingIssue",
    "InterviewPrepResponse",
    "InterviewQuestion",
    "KeywordChartData",
    "RewriteEntry",
    "RewriteHeader",
    "RewriteResponse",
    "RewriteSection",
    "SkillGap",
    "SkillOverlapData",
    "TrackerApplication",
]
